### PR TITLE
New Reports Behavior

### PR DESCRIPTION
**Pull request by douglasg14b**
### Added:
* All (I think) model classes in reports. Modeled after the Java Client
* Base Reports Requests
* User Reports Requests
* All user reports (excluding Drilldown)

### Fixed:
* Requests would only add `DateTime`s to Nv is they did not have a value, resulting in an exception.
* Search request had capitalized `SortOrder` instead of `sortOrder`

### Notes:

I tried to keep the classes modeled in a similar way to yours. However, with reports all the arguments such as the user ID are added as parameters to the URL instead of in the URL (ie. `reports/user.json?user=99999` `vs users/99999.json`). To avoid having to rewrite your `ToQueryString()` method to handle already initialized parameters (among other things) I opted to just use request with constructors as the argument.

Reports also used a lot of the same type names as the rest of the API. To work with this I have opted to use namespace paths to avoid the type confusion. You may have a better solution (renaming the classes to be a bit more unique?)

I only needed the user reports, so that's all I went ahead and did. If I feel compelled, and you accept my work, I may write up more at a later date.

All the new methods have been tested. They should all work fine.

### Additional Potential:

The requests I am using can be further expanded to have their non-required request parameters added to their constructors defaulted to null.

**This May be clear as mud:**
Alternatively the requests could require all of their parameters. And instead of the methods in `HelpScoutClient` would require the use of their lowest required base request (ie. A `UserViewByRequest` request really only requires the UserID, StartDate, and EndDate to function, which is provided by it's base class `UserRequest`). In the example, the method would require a `UserRequest` but a `UserViewByRequest` can also be used, using a `UserViewByRequest` would require the parameter to define the `ViewBy` property.

Obviously this would require the methods to be generic, and constrained with a `where` keyword to prevent users from making incorrect requests. (ie. `GetUserReplies<T>(T requestArg) where T: UserViewByRequest, UserRequest`)

I'm honest not sure if the above behavior would be better or worse for users...

### CODE REVIEW

**Comment by douglasg14b** [comment]
Anything wrong with this? It's been sitting for a while :/

**Comment by mathieukempe** [comment]
Sorry for the delay! I will push the new version to nuget now

**Comment by douglasg14b** [comment]
Sweet, thanks! If you plan on adding the remainder of reports (past user) let me know to make sure I don't start working on it at the same time ;)

**Comment by mathieukempe** [comment]
Thanks for letting me know.
I'll update the readme. I won't have much time in the coming week as I'll be away for 2 weeks

**Pull request merged**
